package bezeq;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "id")
   private int id;

   public MyObject()
   {
   }

   public int getId()
   {
      return this.id;
   }

   public void setId(int id)
   {
      this.id = id;
   }

   public MyObject(int id)
   {
      this.id = id;
   }

}