package bezeq;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Utils implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public static String MY_CONST = "TEST22222";

    public Utils() {
    }


}